version: '3'

services:
  db:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=${DATABASE_NAME}
      - MONGO_INITDB_ROOT_USERNAME=${DATABASE_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "27001:27017"
    volumes:
      - ./db:/data/db
    restart: always
